[build]
  functions = "functions"

[dev]
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[functions.subscribe]
  included_files = ["functions/subscribe.js"]
  external_node_modules = ["mongoose"]